name: neumorphic
description: Neumorphic UI. Implementation of Neumorphism user interface consisting of sets of principles and widgets for the Flutter framework
version: 0.4.0
homepage: https://github.com/neumorphic/neumorphic

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  characters: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0